# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_UI/list_avance_pop_up_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(422, 753)
        self.lineEdit_age_min = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_age_min.setGeometry(QtCore.QRect(10, 40, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_age_min.setFont(font)
        self.lineEdit_age_min.setText("")
        self.lineEdit_age_min.setObjectName("lineEdit_age_min")
        self.label_titre_age_min = QtWidgets.QLabel(Dialog)
        self.label_titre_age_min.setGeometry(QtCore.QRect(10, 10, 371, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_titre_age_min.setFont(font)
        self.label_titre_age_min.setObjectName("label_titre_age_min")
        self.label_titre_age_max = QtWidgets.QLabel(Dialog)
        self.label_titre_age_max.setGeometry(QtCore.QRect(160, 10, 371, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_titre_age_max.setFont(font)
        self.label_titre_age_max.setObjectName("label_titre_age_max")
        self.lineEdit_age_max = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_age_max.setGeometry(QtCore.QRect(160, 40, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_age_max.setFont(font)
        self.lineEdit_age_max.setText("")
        self.lineEdit_age_max.setObjectName("lineEdit_age_max")
        self.pushButton_age_rechercher = QtWidgets.QPushButton(Dialog)
        self.pushButton_age_rechercher.setGeometry(QtCore.QRect(300, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_age_rechercher.setFont(font)
        self.pushButton_age_rechercher.setObjectName("pushButton_age_rechercher")
        self.listView_list_patient_avance = QtWidgets.QListView(Dialog)
        self.listView_list_patient_avance.setGeometry(QtCore.QRect(30, 100, 351, 541))
        self.listView_list_patient_avance.setObjectName("listView_list_patient_avance")
        self.pushButton_hide_list_avance = QtWidgets.QPushButton(Dialog)
        self.pushButton_hide_list_avance.setGeometry(QtCore.QRect(280, 680, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_hide_list_avance.setFont(font)
        self.pushButton_hide_list_avance.setObjectName("pushButton_hide_list_avance")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_titre_age_min.setText(_translate("Dialog", "Age Minimum"))
        self.label_titre_age_max.setText(_translate("Dialog", "Age Maximum"))
        self.pushButton_age_rechercher.setText(_translate("Dialog", "Rechercher"))
        self.pushButton_hide_list_avance.setText(_translate("Dialog", "fermer"))
